[project]
name = "fluxbio-sanctuary-core"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/fluxbio-sanctuary-core/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.fluxbio-sanctuary-core]
path = "contracts/fluxbio-sanctuary-core.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
